# Generated by Django 6.0.3 on 2026-04-21 13:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Validation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documentverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phoneverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='verificationlog',
            name='user',
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone OTP',
                'verbose_name_plural': 'Phone OTPs',
            },
        ),
        migrations.DeleteModel(
            name='AddressVerification',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='DocumentVerification',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.DeleteModel(
            name='KYCVerification',
        ),
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
        migrations.DeleteModel(
            name='VerificationLog',
        ),
    ]
