# Generated by Django 6.0.3 on 2026-04-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsettings',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='sms_alerts',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
